image: debian/stable
packages:
  - composer
  - php-curl
  - php-date
  - php-mbstring
  - php-pdo-sqlite
  - php-intl
  - php-dom
  - php-gmp
sources:
  -  https://git.sr.ht/~fkooman/vpn-user-portal
tasks:
  - setup: |
      cd vpn-user-portal
      composer update
  - build: |
      cd vpn-user-portal
      vendor/bin/put
